### ISSUE TITLE
Redesign and functionality search (list)

### ISSUE THREAD

**Issue by tomkunzler** [openstate/ori-search#7]
This is a note-to self with some things that could be enhanced concerning the ORI-search. We can work on redesign of the search-platform from april-june with funds from Dutch provinces. We have 5.000 euro to work out a redesign for provinces and add extra functionality. This can be ported back to municipalities. These are just wishes, we need to see what is achievable and do-able within the budget.

1: New redesign in line with OSF-design (like openspending.nl and openwob.nl)
2: New front page (with participants tile --> choose municipality/province) and search engine redesign. Design needs to be made by Nadji or Bart (to do!) too make it more intuitive 
3: Better selection of date/time (date range)
4: Better selection of document type, (deselect/select) and don't give a 0 when you deslect a document type
5: Automatic sorting for most recent instead of most relevant
6: Maybe make it more like a dashboard that highlights data or shows the number of participating governments, number of document etc. 
7: Add VNG and Argu logo's 
8: Add city council member data from Almanak?
9: More to follow just an idea box.

**Comment by breyten** [comment]
👍 

Just for clarification purposes:

* Re. 3. What would be a better date selection?
* Re. 6. Do you want me to make a map with markers again like OpenSpending? ;)

Also in general:
* better on mobile (Ie. filters on mobile too)

**Comment by tomkunzler** [comment]
3: See how WaarOverheid is doing the data selection (with a slider). Its more intuitive. Plus for some municipaliaties even though they only have data from 2013 onwards, it still shows 2006 as starting point for selection
6: No, no markers, because it looks messy. But something prettier, doesn't have to be a map. But maybe like Open Spending now a list that can fold based on province. Or a map with municipal boundaries which also shows participants and a municipality has a colour when it is in the data. Like the CartoDB map we have on https://openstate.eu/nl/2018/02/open-raadsinformatie-100-gemeenten-beschikbaar-via-app-waaroverheid/

Mobile I agree completely 

And HTTPS adoption! Practice what you preach

**Comment by tomkunzler** [comment]
When searching through data of multiple governments you cannot see to which government a search result belongs. Formerly we used the logo of the municipality, but now we just use the first letter of the municipalities. It should be clear by a logo or a text from which municipality/government the data comes.

**Comment by tomkunzler** [comment]
Redirect the link in the search to www.openraadsinformatie.nl to https://www.da2020.nl/ondersteuningsmiddelen/pilots-open-raadsinformatie (just make openraadsinformatie.nl a redirect to https://www.da2020.nl/ondersteuningsmiddelen/pilots-open-raadsinformatie)

**Comment by breyten** [comment]
Redirect to VNG page now works

**Comment by tomkunzler** [comment]
Add a link in the menu bar of zoek.openraadsinformatie.nl to WaarOverheid with the name 'Raadsinformatie op de kaart' which links to https://waaroverheid.nl/
